#pragma once

// General
#define EQ_ALTERNATE_ABILITY_IDENTIFY    346
#define EQ_ALTERNATE_ABILITY_ORIGIN      331

// Special
#define EQ_ALTERNATE_ABILITY_ARMOR_OF_EXPERIENCE                     2000
#define EQ_ALTERNATE_ABILITY_BANESTRIKE                              15073
#define EQ_ALTERNATE_ABILITY_CHAOTIC_JESTER                          483
#define EQ_ALTERNATE_ABILITY_EXPEDIENT_RECOVERY                      484
#define EQ_ALTERNATE_ABILITY_GLYPH_OF_ANGRY_THOUGHTS                 5004
#define EQ_ALTERNATE_ABILITY_GLYPH_OF_ARCANE_SECRETS                 587
#define EQ_ALTERNATE_ABILITY_GLYPH_OF_COURAGE                        5000
#define EQ_ALTERNATE_ABILITY_GLYPH_OF_DESTRUCTION_I                  4706
#define EQ_ALTERNATE_ABILITY_GLYPH_OF_DESTRUCTION_II                 7019
#define EQ_ALTERNATE_ABILITY_GLYPH_OF_DRACONIC_POTENTIAL_I           4705
#define EQ_ALTERNATE_ABILITY_GLYPH_OF_DRACONIC_POTENTIAL_II          7018
#define EQ_ALTERNATE_ABILITY_GLYPH_OF_DRAGON_SCALES_I                4702
#define EQ_ALTERNATE_ABILITY_GLYPH_OF_DRAGON_SCALES_II               7016
#define EQ_ALTERNATE_ABILITY_GLYPH_OF_FIREWORKS_I                    586
#define EQ_ALTERNATE_ABILITY_GLYPH_OF_FIREWORKS_II                   897
#define EQ_ALTERNATE_ABILITY_GLYPH_OF_STORED_LIFE                    5002
#define EQ_ALTERNATE_ABILITY_HARMONIC_DISSONANCE                     574
#define EQ_ALTERNATE_ABILITY_INFUSION_OF_THE_FAITHFUL                482
#define EQ_ALTERNATE_ABILITY_INTENSITY_OF_THE_RESOLUTE               487
#define EQ_ALTERNATE_ABILITY_LESSON_OF_THE_DEVOTED                   481
#define EQ_ALTERNATE_ABILITY_STAUNCH_RECOVERY                        486
#define EQ_ALTERNATE_ABILITY_STEADFAST_SERVANT                       485
#define EQ_ALTERNATE_ABILITY_SUMMON_CLOCKWORK_BANKER                 8130
#define EQ_ALTERNATE_ABILITY_SUMMON_PERMUTATION_PEDDLER              453
#define EQ_ALTERNATE_ABILITY_SUMMON_PERSONAL_TRIBUTE_MASTER          182
#define EQ_ALTERNATE_ABILITY_SUMMON_RESUPPLY_AGENT                   8081
#define EQ_ALTERNATE_ABILITY_SUMMON_TOME_OF_THE_HEROS_JOURNEY        1687
#define EQ_ALTERNATE_ABILITY_THRONE_OF_HEROES                        511

// Archetype
#define EQ_ALTERNATE_ABILITY_BATTLE_LEAP         611
#define EQ_ALTERNATE_ABILITY_FURIOUS_LEAP        3899
#define EQ_ALTERNATE_ABILITY_GRAPPLING_STRIKE    601
#define EQ_ALTERNATE_ABILITY_HOLD_THE_LINE       734
#define EQ_ALTERNATE_ABILITY_RAMPAGE             109
#define EQ_ALTERNATE_ABILITY_VEHEMENT_RAGE       800

// Class: Warrior
#define EQ_ALTERNATE_ABILITY_AREA_TAUNT                 110
#define EQ_ALTERNATE_ABILITY_BLAST_OF_ANGER             3646
#define EQ_ALTERNATE_ABILITY_CALL_OF_CHALLENGE          552
#define EQ_ALTERNATE_ABILITY_GUT_PUNCH                  3732
#define EQ_ALTERNATE_ABILITY_KNEE_STRIKE                801
#define EQ_ALTERNATE_ABILITY_MARK_OF_THE_MAGE_HUNTER    606
#define EQ_ALTERNATE_ABILITY_PRESS_THE_ATTACK           467
#define EQ_ALTERNATE_ABILITY_RESPLENDANT_GLORY          130
#define EQ_ALTERNATE_ABILITY_WAR_CRY                    111
#define EQ_ALTERNATE_ABILITY_WARLORDS_TENACITY          300

// Class: Cleric
#define EQ_ALTERNATE_ABILITY_BESTOW_DIVINE_AURA_BEZA    1061
#define EQ_ALTERNATE_ABILITY_DIVINE_RETRIBUTION         392
#define EQ_ALTERNATE_ABILITY_EXQUISITE_BENEDICTION      255
#define EQ_ALTERNATE_ABILITY_SANCTUARY                  396

// Class: Enchanter

// Class: Druid

// Class: Bard

// Class: Berserker

