#pragma once

// ExecuteCmd() function command IDs

// Find: (.*?")(.*?)(")
// Replace: \2

constexpr auto EQ_EXECUTECMD_BEGIN_LINE = __LINE__;
#define EQ_EXECUTECMD_AUTORUN                                                     0
#define EQ_EXECUTECMD_JUMP                                                        1
#define EQ_EXECUTECMD_FORWARD                                                     2
#define EQ_EXECUTECMD_BACK                                                        3
#define EQ_EXECUTECMD_RIGHT                                                       4
#define EQ_EXECUTECMD_LEFT                                                        5
#define EQ_EXECUTECMD_STRAFE_LEFT                                                 6
#define EQ_EXECUTECMD_STRAFE_RIGHT                                                7
#define EQ_EXECUTECMD_MOUSELOOK                                                   8
#define EQ_EXECUTECMD_MOUSELOOK_ENGAGE                                            9
#define EQ_EXECUTECMD_AUTOPRIM                                                    10
#define EQ_EXECUTECMD_CONSIDER                                                    11
#define EQ_EXECUTECMD_DUCK                                                        12
#define EQ_EXECUTECMD_HAIL                                                        13
#define EQ_EXECUTECMD_INVENTORY                                                   14
#define EQ_EXECUTECMD_TELL                                                        15
#define EQ_EXECUTECMD_USE                                                         16
#define EQ_EXECUTECMD_PITCHUP                                                     17
#define EQ_EXECUTECMD_PITCHDOWN                                                   18
#define EQ_EXECUTECMD_CENTERVIEW                                                  19
#define EQ_EXECUTECMD_ZOOMIN                                                      20
#define EQ_EXECUTECMD_ZOOMOUT                                                     21
#define EQ_EXECUTECMD_TOGGLECAM                                                   22
#define EQ_EXECUTECMD_FULLSCREEN                                                  23
#define EQ_EXECUTECMD_TARGETME                                                    24
#define EQ_EXECUTECMD_PARTY1                                                      25
#define EQ_EXECUTECMD_PARTY2                                                      26
#define EQ_EXECUTECMD_PARTY3                                                      27
#define EQ_EXECUTECMD_PARTY4                                                      28
#define EQ_EXECUTECMD_PARTY5                                                      29
#define EQ_EXECUTECMD_TARGETPC                                                    30
#define EQ_EXECUTECMD_CYCLEPCTARGETS                                              31
#define EQ_EXECUTECMD_TARGETNPC                                                   32
#define EQ_EXECUTECMD_CYCLENPCTARGETS                                             33
#define EQ_EXECUTECMD_TARGETCORPSE                                                34
#define EQ_EXECUTECMD_CYCLECORPSETARGETS                                          35
#define EQ_EXECUTECMD_NETSTAT                                                     36
#define EQ_EXECUTECMD_HOT1_1                                                      37
#define EQ_EXECUTECMD_HOT1_2                                                      38
#define EQ_EXECUTECMD_HOT1_3                                                      39
#define EQ_EXECUTECMD_HOT1_4                                                      40
#define EQ_EXECUTECMD_HOT1_5                                                      41
#define EQ_EXECUTECMD_HOT1_6                                                      42
#define EQ_EXECUTECMD_HOT1_7                                                      43
#define EQ_EXECUTECMD_HOT1_8                                                      44
#define EQ_EXECUTECMD_HOT1_9                                                      45
#define EQ_EXECUTECMD_HOT1_10                                                     46
#define EQ_EXECUTECMD_HOT1_11                                                     47
#define EQ_EXECUTECMD_HOT1_12                                                     48
#define EQ_EXECUTECMD_HOT2_1                                                      49
#define EQ_EXECUTECMD_HOT2_2                                                      50
#define EQ_EXECUTECMD_HOT2_3                                                      51
#define EQ_EXECUTECMD_HOT2_4                                                      52
#define EQ_EXECUTECMD_HOT2_5                                                      53
#define EQ_EXECUTECMD_HOT2_6                                                      54
#define EQ_EXECUTECMD_HOT2_7                                                      55
#define EQ_EXECUTECMD_HOT2_8                                                      56
#define EQ_EXECUTECMD_HOT2_9                                                      57
#define EQ_EXECUTECMD_HOT2_10                                                     58
#define EQ_EXECUTECMD_HOT2_11                                                     59
#define EQ_EXECUTECMD_HOT2_12                                                     60
#define EQ_EXECUTECMD_HOT3_1                                                      61
#define EQ_EXECUTECMD_HOT3_2                                                      62
#define EQ_EXECUTECMD_HOT3_3                                                      63
#define EQ_EXECUTECMD_HOT3_4                                                      64
#define EQ_EXECUTECMD_HOT3_5                                                      65
#define EQ_EXECUTECMD_HOT3_6                                                      66
#define EQ_EXECUTECMD_HOT3_7                                                      67
#define EQ_EXECUTECMD_HOT3_8                                                      68
#define EQ_EXECUTECMD_HOT3_9                                                      69
#define EQ_EXECUTECMD_HOT3_10                                                     70
#define EQ_EXECUTECMD_HOT3_11                                                     71
#define EQ_EXECUTECMD_HOT3_12                                                     72
#define EQ_EXECUTECMD_HOT4_1                                                      73
#define EQ_EXECUTECMD_HOT4_2                                                      74
#define EQ_EXECUTECMD_HOT4_3                                                      75
#define EQ_EXECUTECMD_HOT4_4                                                      76
#define EQ_EXECUTECMD_HOT4_5                                                      77
#define EQ_EXECUTECMD_HOT4_6                                                      78
#define EQ_EXECUTECMD_HOT4_7                                                      79
#define EQ_EXECUTECMD_HOT4_8                                                      80
#define EQ_EXECUTECMD_HOT4_9                                                      81
#define EQ_EXECUTECMD_HOT4_10                                                     82
#define EQ_EXECUTECMD_HOT4_11                                                     83
#define EQ_EXECUTECMD_HOT4_12                                                     84
#define EQ_EXECUTECMD_HOT5_1                                                      85
#define EQ_EXECUTECMD_HOT5_2                                                      86
#define EQ_EXECUTECMD_HOT5_3                                                      87
#define EQ_EXECUTECMD_HOT5_4                                                      88
#define EQ_EXECUTECMD_HOT5_5                                                      89
#define EQ_EXECUTECMD_HOT5_6                                                      90
#define EQ_EXECUTECMD_HOT5_7                                                      91
#define EQ_EXECUTECMD_HOT5_8                                                      92
#define EQ_EXECUTECMD_HOT5_9                                                      93
#define EQ_EXECUTECMD_HOT5_10                                                     94
#define EQ_EXECUTECMD_HOT5_11                                                     95
#define EQ_EXECUTECMD_HOT5_12                                                     96
#define EQ_EXECUTECMD_HOT6_1                                                      97
#define EQ_EXECUTECMD_HOT6_2                                                      98
#define EQ_EXECUTECMD_HOT6_3                                                      99
#define EQ_EXECUTECMD_HOT6_4                                                      100
#define EQ_EXECUTECMD_HOT6_5                                                      101
#define EQ_EXECUTECMD_HOT6_6                                                      102
#define EQ_EXECUTECMD_HOT6_7                                                      103
#define EQ_EXECUTECMD_HOT6_8                                                      104
#define EQ_EXECUTECMD_HOT6_9                                                      105
#define EQ_EXECUTECMD_HOT6_10                                                     106
#define EQ_EXECUTECMD_HOT6_11                                                     107
#define EQ_EXECUTECMD_HOT6_12                                                     108
#define EQ_EXECUTECMD_HOT7_1                                                      109
#define EQ_EXECUTECMD_HOT7_2                                                      110
#define EQ_EXECUTECMD_HOT7_3                                                      111
#define EQ_EXECUTECMD_HOT7_4                                                      112
#define EQ_EXECUTECMD_HOT7_5                                                      113
#define EQ_EXECUTECMD_HOT7_6                                                      114
#define EQ_EXECUTECMD_HOT7_7                                                      115
#define EQ_EXECUTECMD_HOT7_8                                                      116
#define EQ_EXECUTECMD_HOT7_9                                                      117
#define EQ_EXECUTECMD_HOT7_10                                                     118
#define EQ_EXECUTECMD_HOT7_11                                                     119
#define EQ_EXECUTECMD_HOT7_12                                                     120
#define EQ_EXECUTECMD_HOT8_1                                                      121
#define EQ_EXECUTECMD_HOT8_2                                                      122
#define EQ_EXECUTECMD_HOT8_3                                                      123
#define EQ_EXECUTECMD_HOT8_4                                                      124
#define EQ_EXECUTECMD_HOT8_5                                                      125
#define EQ_EXECUTECMD_HOT8_6                                                      126
#define EQ_EXECUTECMD_HOT8_7                                                      127
#define EQ_EXECUTECMD_HOT8_8                                                      128
#define EQ_EXECUTECMD_HOT8_9                                                      129
#define EQ_EXECUTECMD_HOT8_10                                                     130
#define EQ_EXECUTECMD_HOT8_11                                                     131
#define EQ_EXECUTECMD_HOT8_12                                                     132
#define EQ_EXECUTECMD_HOT9_1                                                      133
#define EQ_EXECUTECMD_HOT9_2                                                      134
#define EQ_EXECUTECMD_HOT9_3                                                      135
#define EQ_EXECUTECMD_HOT9_4                                                      136
#define EQ_EXECUTECMD_HOT9_5                                                      137
#define EQ_EXECUTECMD_HOT9_6                                                      138
#define EQ_EXECUTECMD_HOT9_7                                                      139
#define EQ_EXECUTECMD_HOT9_8                                                      140
#define EQ_EXECUTECMD_HOT9_9                                                      141
#define EQ_EXECUTECMD_HOT9_10                                                     142
#define EQ_EXECUTECMD_HOT9_11                                                     143
#define EQ_EXECUTECMD_HOT9_12                                                     144
#define EQ_EXECUTECMD_HOT10_1                                                     145
#define EQ_EXECUTECMD_HOT10_2                                                     146
#define EQ_EXECUTECMD_HOT10_3                                                     147
#define EQ_EXECUTECMD_HOT10_4                                                     148
#define EQ_EXECUTECMD_HOT10_5                                                     149
#define EQ_EXECUTECMD_HOT10_6                                                     150
#define EQ_EXECUTECMD_HOT10_7                                                     151
#define EQ_EXECUTECMD_HOT10_8                                                     152
#define EQ_EXECUTECMD_HOT10_9                                                     153
#define EQ_EXECUTECMD_HOT10_10                                                    154
#define EQ_EXECUTECMD_HOT10_11                                                    155
#define EQ_EXECUTECMD_HOT10_12                                                    156
#define EQ_EXECUTECMD_HOT11_1                                                     157
#define EQ_EXECUTECMD_HOT11_2                                                     158
#define EQ_EXECUTECMD_HOT11_3                                                     159
#define EQ_EXECUTECMD_HOT11_4                                                     160
#define EQ_EXECUTECMD_HOT11_5                                                     161
#define EQ_EXECUTECMD_HOT11_6                                                     162
#define EQ_EXECUTECMD_HOT11_7                                                     163
#define EQ_EXECUTECMD_HOT11_8                                                     164
#define EQ_EXECUTECMD_HOT11_9                                                     165
#define EQ_EXECUTECMD_HOT11_10                                                    166
#define EQ_EXECUTECMD_HOT11_11                                                    167
#define EQ_EXECUTECMD_HOT11_12                                                    168
#define EQ_EXECUTECMD_HOTPAGE1_1                                                  169
#define EQ_EXECUTECMD_HOTPAGE1_2                                                  170
#define EQ_EXECUTECMD_HOTPAGE1_3                                                  171
#define EQ_EXECUTECMD_HOTPAGE1_4                                                  172
#define EQ_EXECUTECMD_HOTPAGE1_5                                                  173
#define EQ_EXECUTECMD_HOTPAGE1_6                                                  174
#define EQ_EXECUTECMD_HOTPAGE1_7                                                  175
#define EQ_EXECUTECMD_HOTPAGE1_8                                                  176
#define EQ_EXECUTECMD_HOTPAGE1_9                                                  177
#define EQ_EXECUTECMD_HOTPAGE1_10                                                 178
#define EQ_EXECUTECMD_HOTPAGE2_1                                                  179
#define EQ_EXECUTECMD_HOTPAGE2_2                                                  180
#define EQ_EXECUTECMD_HOTPAGE2_3                                                  181
#define EQ_EXECUTECMD_HOTPAGE2_4                                                  182
#define EQ_EXECUTECMD_HOTPAGE2_5                                                  183
#define EQ_EXECUTECMD_HOTPAGE2_6                                                  184
#define EQ_EXECUTECMD_HOTPAGE2_7                                                  185
#define EQ_EXECUTECMD_HOTPAGE2_8                                                  186
#define EQ_EXECUTECMD_HOTPAGE2_9                                                  187
#define EQ_EXECUTECMD_HOTPAGE2_10                                                 188
#define EQ_EXECUTECMD_HOTPAGE3_1                                                  189
#define EQ_EXECUTECMD_HOTPAGE3_2                                                  190
#define EQ_EXECUTECMD_HOTPAGE3_3                                                  191
#define EQ_EXECUTECMD_HOTPAGE3_4                                                  192
#define EQ_EXECUTECMD_HOTPAGE3_5                                                  193
#define EQ_EXECUTECMD_HOTPAGE3_6                                                  194
#define EQ_EXECUTECMD_HOTPAGE3_7                                                  195
#define EQ_EXECUTECMD_HOTPAGE3_8                                                  196
#define EQ_EXECUTECMD_HOTPAGE3_9                                                  197
#define EQ_EXECUTECMD_HOTPAGE3_10                                                 198
#define EQ_EXECUTECMD_HOTPAGE4_1                                                  199
#define EQ_EXECUTECMD_HOTPAGE4_2                                                  200
#define EQ_EXECUTECMD_HOTPAGE4_3                                                  201
#define EQ_EXECUTECMD_HOTPAGE4_4                                                  202
#define EQ_EXECUTECMD_HOTPAGE4_5                                                  203
#define EQ_EXECUTECMD_HOTPAGE4_6                                                  204
#define EQ_EXECUTECMD_HOTPAGE4_7                                                  205
#define EQ_EXECUTECMD_HOTPAGE4_8                                                  206
#define EQ_EXECUTECMD_HOTPAGE4_9                                                  207
#define EQ_EXECUTECMD_HOTPAGE4_10                                                 208
#define EQ_EXECUTECMD_HOTPAGE5_1                                                  209
#define EQ_EXECUTECMD_HOTPAGE5_2                                                  210
#define EQ_EXECUTECMD_HOTPAGE5_3                                                  211
#define EQ_EXECUTECMD_HOTPAGE5_4                                                  212
#define EQ_EXECUTECMD_HOTPAGE5_5                                                  213
#define EQ_EXECUTECMD_HOTPAGE5_6                                                  214
#define EQ_EXECUTECMD_HOTPAGE5_7                                                  215
#define EQ_EXECUTECMD_HOTPAGE5_8                                                  216
#define EQ_EXECUTECMD_HOTPAGE5_9                                                  217
#define EQ_EXECUTECMD_HOTPAGE5_10                                                 218
#define EQ_EXECUTECMD_HOTPAGE6_1                                                  219
#define EQ_EXECUTECMD_HOTPAGE6_2                                                  220
#define EQ_EXECUTECMD_HOTPAGE6_3                                                  221
#define EQ_EXECUTECMD_HOTPAGE6_4                                                  222
#define EQ_EXECUTECMD_HOTPAGE6_5                                                  223
#define EQ_EXECUTECMD_HOTPAGE6_6                                                  224
#define EQ_EXECUTECMD_HOTPAGE6_7                                                  225
#define EQ_EXECUTECMD_HOTPAGE6_8                                                  226
#define EQ_EXECUTECMD_HOTPAGE6_9                                                  227
#define EQ_EXECUTECMD_HOTPAGE6_10                                                 228
#define EQ_EXECUTECMD_HOTPAGE7_1                                                  229
#define EQ_EXECUTECMD_HOTPAGE7_2                                                  230
#define EQ_EXECUTECMD_HOTPAGE7_3                                                  231
#define EQ_EXECUTECMD_HOTPAGE7_4                                                  232
#define EQ_EXECUTECMD_HOTPAGE7_5                                                  233
#define EQ_EXECUTECMD_HOTPAGE7_6                                                  234
#define EQ_EXECUTECMD_HOTPAGE7_7                                                  235
#define EQ_EXECUTECMD_HOTPAGE7_8                                                  236
#define EQ_EXECUTECMD_HOTPAGE7_9                                                  237
#define EQ_EXECUTECMD_HOTPAGE7_10                                                 238
#define EQ_EXECUTECMD_HOTPAGE8_1                                                  239
#define EQ_EXECUTECMD_HOTPAGE8_2                                                  240
#define EQ_EXECUTECMD_HOTPAGE8_3                                                  241
#define EQ_EXECUTECMD_HOTPAGE8_4                                                  242
#define EQ_EXECUTECMD_HOTPAGE8_5                                                  243
#define EQ_EXECUTECMD_HOTPAGE8_6                                                  244
#define EQ_EXECUTECMD_HOTPAGE8_7                                                  245
#define EQ_EXECUTECMD_HOTPAGE8_8                                                  246
#define EQ_EXECUTECMD_HOTPAGE8_9                                                  247
#define EQ_EXECUTECMD_HOTPAGE8_10                                                 248
#define EQ_EXECUTECMD_HOTPAGE9_1                                                  249
#define EQ_EXECUTECMD_HOTPAGE9_2                                                  250
#define EQ_EXECUTECMD_HOTPAGE9_3                                                  251
#define EQ_EXECUTECMD_HOTPAGE9_4                                                  252
#define EQ_EXECUTECMD_HOTPAGE9_5                                                  253
#define EQ_EXECUTECMD_HOTPAGE9_6                                                  254
#define EQ_EXECUTECMD_HOTPAGE9_7                                                  255
#define EQ_EXECUTECMD_HOTPAGE9_8                                                  256
#define EQ_EXECUTECMD_HOTPAGE9_9                                                  257
#define EQ_EXECUTECMD_HOTPAGE9_10                                                 258
#define EQ_EXECUTECMD_HOTPAGE10_1                                                 259
#define EQ_EXECUTECMD_HOTPAGE10_2                                                 260
#define EQ_EXECUTECMD_HOTPAGE10_3                                                 261
#define EQ_EXECUTECMD_HOTPAGE10_4                                                 262
#define EQ_EXECUTECMD_HOTPAGE10_5                                                 263
#define EQ_EXECUTECMD_HOTPAGE10_6                                                 264
#define EQ_EXECUTECMD_HOTPAGE10_7                                                 265
#define EQ_EXECUTECMD_HOTPAGE10_8                                                 266
#define EQ_EXECUTECMD_HOTPAGE10_9                                                 267
#define EQ_EXECUTECMD_HOTPAGE10_10                                                268
#define EQ_EXECUTECMD_HOTPAGE11_1                                                 269
#define EQ_EXECUTECMD_HOTPAGE11_2                                                 270
#define EQ_EXECUTECMD_HOTPAGE11_3                                                 271
#define EQ_EXECUTECMD_HOTPAGE11_4                                                 272
#define EQ_EXECUTECMD_HOTPAGE11_5                                                 273
#define EQ_EXECUTECMD_HOTPAGE11_6                                                 274
#define EQ_EXECUTECMD_HOTPAGE11_7                                                 275
#define EQ_EXECUTECMD_HOTPAGE11_8                                                 276
#define EQ_EXECUTECMD_HOTPAGE11_9                                                 277
#define EQ_EXECUTECMD_HOTPAGE11_10                                                278
#define EQ_EXECUTECMD_CAST1                                                       279
#define EQ_EXECUTECMD_CAST2                                                       280
#define EQ_EXECUTECMD_CAST3                                                       281
#define EQ_EXECUTECMD_CAST4                                                       282
#define EQ_EXECUTECMD_CAST5                                                       283
#define EQ_EXECUTECMD_CAST6                                                       284
#define EQ_EXECUTECMD_CAST7                                                       285
#define EQ_EXECUTECMD_CAST8                                                       286
#define EQ_EXECUTECMD_CAST9                                                       287
#define EQ_EXECUTECMD_CAST10                                                      288
#define EQ_EXECUTECMD_CAST11                                                      289
#define EQ_EXECUTECMD_CAST12                                                      290
#define EQ_EXECUTECMD_CAST13                                                      291
#define EQ_EXECUTECMD_CAST14                                                      292
#define EQ_EXECUTECMD_REPLY                                                       293
#define EQ_EXECUTECMD_CYCLEREPLY                                                  294
#define EQ_EXECUTECMD_CYCLEREPLY_BACK                                             295
#define EQ_EXECUTECMD_BACKDROP                                                    296
#define EQ_EXECUTECMD_TOGGLETARGET                                                297
#define EQ_EXECUTECMD_SPELLBOOK                                                   298
#define EQ_EXECUTECMD_ABILITIES                                                   299
#define EQ_EXECUTECMD_COMBAT                                                      300
#define EQ_EXECUTECMD_SOCIALS                                                     301
#define EQ_EXECUTECMD_MAIN                                                        302
#define EQ_EXECUTECMD_WHO                                                         303
#define EQ_EXECUTECMD_INVITE_FOLLOW                                               304
#define EQ_EXECUTECMD_DISBAND                                                     305
#define EQ_EXECUTECMD_CAMP                                                        306
#define EQ_EXECUTECMD_SIT_STAND                                                   307
#define EQ_EXECUTECMD_RUN_WALK                                                    308
#define EQ_EXECUTECMD_CLIP_IN                                                     309
#define EQ_EXECUTECMD_CLIP_OUT                                                    310
#define EQ_EXECUTECMD_VOICE_ON                                                    311
#define EQ_EXECUTECMD_SCREENCAP                                                   312
#define EQ_EXECUTECMD_HISTORY_UP                                                  313
#define EQ_EXECUTECMD_HISTORY_DOWN                                                314
#define EQ_EXECUTECMD_PAGEUP                                                      315
#define EQ_EXECUTECMD_PAGEDOWN                                                    316
#define EQ_EXECUTECMD_CMDMODE_SAY                                                 317
#define EQ_EXECUTECMD_CMDMODE_EMOTE                                               318
#define EQ_EXECUTECMD_LOCK_WINDOWS                                                319
#define EQ_EXECUTECMD_TOGGLE_PLAYERWIN                                            320
#define EQ_EXECUTECMD_TOGGLE_PARTYWIN                                             321
#define EQ_EXECUTECMD_TOGGLE_TARGETWIN                                            322
#define EQ_EXECUTECMD_TOGGLE_SPELLSWIN                                            323
#define EQ_EXECUTECMD_TOGGLE_BUFFWIN                                              324
#define EQ_EXECUTECMD_TOGGLE_HOTBOX1WIN                                           325
#define EQ_EXECUTECMD_TOGGLE_HOTBOX2WIN                                           326
#define EQ_EXECUTECMD_TOGGLE_HOTBOX3WIN                                           327
#define EQ_EXECUTECMD_TOGGLE_HOTBOX4WIN                                           328
#define EQ_EXECUTECMD_TOGGLE_HOTBOX5WIN                                           329
#define EQ_EXECUTECMD_TOGGLE_HOTBOX6WIN                                           330
#define EQ_EXECUTECMD_TOGGLE_HOTBOX7WIN                                           331
#define EQ_EXECUTECMD_TOGGLE_HOTBOX8WIN                                           332
#define EQ_EXECUTECMD_TOGGLE_HOTBOX9WIN                                           333
#define EQ_EXECUTECMD_TOGGLE_HOTBOX10WIN                                          334
#define EQ_EXECUTECMD_TOGGLE_HOTBOX11WIN                                          335
#define EQ_EXECUTECMD_TOGGLE_CHATWIN                                              336
#define EQ_EXECUTECMD_TOGGLE_MAILWIN                                              337
#define EQ_EXECUTECMD_TOGGLE_MAILCOMPWIN                                          338
#define EQ_EXECUTECMD_TOGGLE_MAINMENUWIN                                          339
#define EQ_EXECUTECMD_TOGGLE_ALTADVWIN                                            340
#define EQ_EXECUTECMD_TOGGLE_BAZAARWIN                                            341
#define EQ_EXECUTECMD_RTARGET                                                     342
#define EQ_EXECUTECMD_TOGGLE_FRIENDSWIN                                           343
#define EQ_EXECUTECMD_TOGGLE_PETINFOWIN                                           344
#define EQ_EXECUTECMD_TOGGLE_OPTIONSWIN                                           345
#define EQ_EXECUTECMD_TOGGLE_HELPWIN                                              346
#define EQ_EXECUTECMD_TOGGLE_SELECTORWIN                                          347
#define EQ_EXECUTECMD_TOGGLE_VIDEOMODEWIN                                         348
#define EQ_EXECUTECMD_TOGGLE_BAZAARSEARCHWIN                                      349
#define EQ_EXECUTECMD_TOGGLE_COMPASSWIN                                           350
#define EQ_EXECUTECMD_TOGGLE_RAIDWIN                                              351
#define EQ_EXECUTECMD_TOGGLE_MUSICPLAYERWIN                                       352
#define EQ_EXECUTECMD_FORWARD_CAM                                                 353
#define EQ_EXECUTECMD_BACK_CAM                                                    354
#define EQ_EXECUTECMD_RIGHT_CAM                                                   355
#define EQ_EXECUTECMD_LEFT_CAM                                                    356
#define EQ_EXECUTECMD_PITCHUP_CAM                                                 357
#define EQ_EXECUTECMD_PITCHDOWN_CAM                                               358
#define EQ_EXECUTECMD_TOGGLE_JOURNAL                                              359
#define EQ_EXECUTECMD_TOGGLE_SDBUFFWIN                                            360
#define EQ_EXECUTECMD_RELEASE_MOUSE_CURSOR                                        361
#define EQ_EXECUTECMD_TOGGLE_STORYWIN                                             362
#define EQ_EXECUTECMD_TOGGLE_MAPWIN                                               363
#define EQ_EXECUTECMD_TOGGLE_GUILDMGMTWIN                                         364
#define EQ_EXECUTECMD_TOGGLE_FELLOWSHIPWIN                                        365
#define EQ_EXECUTECMD_TOGGLE_LFGROUPWIN                                           366
#define EQ_EXECUTECMD_TOGGLE_LFGUILDWIN                                           367
#define EQ_EXECUTECMD_TOGGLETWOTARGETS                                            368
#define EQ_EXECUTECMD_TOGGLE_CONTEXTMENUS                                         369
#define EQ_EXECUTECMD_FIRST_PERSON_CAMERA                                         370
#define EQ_EXECUTECMD_OVERHEAD_CAMERA                                             371
#define EQ_EXECUTECMD_CHASE_CAMERA                                                372
#define EQ_EXECUTECMD_USER1_CAMERA                                                373
#define EQ_EXECUTECMD_USER2_CAMERA                                                374
#define EQ_EXECUTECMD_TETHER_CAMERA                                               375
#define EQ_EXECUTECMD_TOGGLE_ADVREQUESTWIN                                        376
#define EQ_EXECUTECMD_CLOSE_TOP_WINDOW                                            377
#define EQ_EXECUTECMD_CLEAR_TARGET                                                378
#define EQ_EXECUTECMD_CMD_TOGGLE_FIND_WINDOW                                      379
#define EQ_EXECUTECMD_TOGGLE_LEADERSHIPWIN                                        380
#define EQ_EXECUTECMD_TOGGLE_TRIBUTEBENEFITWIN                                    381
#define EQ_EXECUTECMD_CMD_OPENING_ATTACK1                                         382
#define EQ_EXECUTECMD_CMD_OPENING_ATTACK2                                         383
#define EQ_EXECUTECMD_CMD_OPENING_ATTACK3                                         384
#define EQ_EXECUTECMD_CMD_OPENING_ATTACK4                                         385
#define EQ_EXECUTECMD_CMD_OPENING_ATTACK5                                         386
#define EQ_EXECUTECMD_CMD_OPENING_ATTACK6                                         387
#define EQ_EXECUTECMD_CMD_OPENING_ATTACK7                                         388
#define EQ_EXECUTECMD_CMD_OPENING_ATTACK8                                         389
#define EQ_EXECUTECMD_CMD_TOGGLE_COMBAT_ABILITY_WIN                               390
#define EQ_EXECUTECMD_CMD_TOGGLE_DYNAMIC_ZONE_WIN                                 391
#define EQ_EXECUTECMD_CMD_TOGGLE_PVP_LEADERBOARD                                  392
#define EQ_EXECUTECMD_CMD_TOGGLETASKWIN                                           393
#define EQ_EXECUTECMD_CMD_TOGGLE_TICKET_WND                                       394
#define EQ_EXECUTECMD_CMD_STOP_CAST                                               395
#define EQ_EXECUTECMD_CMD_TOGGLEVOICEWIN                                          396
#define EQ_EXECUTECMD_CMD_TOGGLE_TITLE_WND                                        397
#define EQ_EXECUTECMD_TOGGLE_BANDOLIER                                            398
#define EQ_EXECUTECMD_OPEN_INV_BAGS                                               399
#define EQ_EXECUTECMD_CLOSE_INV_BAGS                                              400
#define EQ_EXECUTECMD_TOGGLE_INV_BAGS                                             401
#define EQ_EXECUTECMD_TOGGLE_SKILLS_WND                                           402
#define EQ_EXECUTECMD_OPEN_ETN_HELP                                               403
#define EQ_EXECUTECMD_CMD_TOGGLE_BLOCKEDBUFFWIN                                   404
#define EQ_EXECUTECMD_CMD_TOGGLE_AUDIO_TRIGGER_WINDOW                             405
#define EQ_EXECUTECMD_CMD_CLIPBOARD_PASTE                                         406
#define EQ_EXECUTECMD_CMD_OPEN_EQPLAYERS                                          407
#define EQ_EXECUTECMD_CMD_TOGGLE_AURAWND                                          408
#define EQ_EXECUTECMD_CMD_TOGGLE_BLOCKEDPETBUFFWIN                                409
#define EQ_EXECUTECMD_CMD_TOGGLE_REWARD_SELECTION_WIN                             410
#define EQ_EXECUTECMD_CMD_TOGGLE_CLAIM_WIN                                        411
#define EQ_EXECUTECMD_CMD_TOGGLE_VOICE_BAR                                        412
#define EQ_EXECUTECMD_CMD_TOGGLE_AS_LIST                                          413
#define EQ_EXECUTECMD_CMD_PUSH_TO_TALK                                            414
#define EQ_EXECUTECMD_CMD_PUSH_TO_TALK_SAY                                        415
#define EQ_EXECUTECMD_CMD_PUSH_TO_TALK_GROUP                                      416
#define EQ_EXECUTECMD_CMD_PUSH_TO_TALK_RAID                                       417
#define EQ_EXECUTECMD_CMD_PUSH_TO_TALK_GUILD                                      418
#define EQ_EXECUTECMD_CMD_MERCENARIES                                             419
#define EQ_EXECUTECMD_CMD_MARKETPLACE                                             420
#define EQ_EXECUTECMD_CMD_WELCOMESCREEN                                           421
#define EQ_EXECUTECMD_CMD_EXTENDED_TARGET_WINDOW                                  422
#define EQ_EXECUTECMD_CMD_ACHIEVEMENT_WINDOW                                      423
#define EQ_EXECUTECMD_TARGET_XTARGET_1                                            424
#define EQ_EXECUTECMD_TARGET_XTARGET_2                                            425
#define EQ_EXECUTECMD_TARGET_XTARGET_3                                            426
#define EQ_EXECUTECMD_TARGET_XTARGET_4                                            427
#define EQ_EXECUTECMD_TARGET_XTARGET_5                                            428
#define EQ_EXECUTECMD_TARGET_XTARGET_6                                            429
#define EQ_EXECUTECMD_TARGET_XTARGET_7                                            430
#define EQ_EXECUTECMD_TARGET_XTARGET_8                                            431
#define EQ_EXECUTECMD_TARGET_XTARGET_9                                            432
#define EQ_EXECUTECMD_TARGET_XTARGET_10                                           433
#define EQ_EXECUTECMD_TARGET_XTARGET_11                                           434
#define EQ_EXECUTECMD_TARGET_XTARGET_12                                           435
#define EQ_EXECUTECMD_TARGET_XTARGET_13                                           436
#define EQ_EXECUTECMD_TARGET_XTARGET_14                                           437
#define EQ_EXECUTECMD_TARGET_XTARGET_15                                           438
#define EQ_EXECUTECMD_TARGET_XTARGET_16                                           439
#define EQ_EXECUTECMD_TARGET_XTARGET_17                                           440
#define EQ_EXECUTECMD_TARGET_XTARGET_18                                           441
#define EQ_EXECUTECMD_TARGET_XTARGET_19                                           442
#define EQ_EXECUTECMD_TARGET_XTARGET_20                                           443
#define EQ_EXECUTECMD_ADD_XTARGET                                                 444
#define EQ_EXECUTECMD_REMOVE_XTARGET                                              445
#define EQ_EXECUTECMD_CYCLE_XTARGET                                               446
#define EQ_EXECUTECMD_REMOVE_XTARGET_BY_SLOT                                      447
#define EQ_EXECUTECMD_CMD_REAL_ESTATE_ITEMS_WINDOW                                448
#define EQ_EXECUTECMD_CMD_REAL_ESTATE_MANAGE_WINDOW                               449
#define EQ_EXECUTECMD_CMD_REAL_ESTATE_TROPHIES_WINDOW                             450
#define EQ_EXECUTECMD_CMD_REAL_ESTATE_PLOT_SEARCH_WINDOW                          451
#define EQ_EXECUTECMD_CMD_REAL_ESTATE_HELP_WINDOW                                 452
#define EQ_EXECUTECMD_CMD_REAL_ESTATE_ITEM_PLACEMENT_1                            453
#define EQ_EXECUTECMD_CMD_REAL_ESTATE_ITEM_PLACEMENT_2                            454
#define EQ_EXECUTECMD_CMD_REAL_ESTATE_ITEM_PLACEMENT_3                            455
#define EQ_EXECUTECMD_CMD_REAL_ESTATE_ITEM_PLACEMENT_4                            456
#define EQ_EXECUTECMD_CMD_REAL_ESTATE_ITEM_PLACEMENT_5                            457
#define EQ_EXECUTECMD_CMD_REAL_ESTATE_ITEM_PLACEMENT_6                            458
#define EQ_EXECUTECMD_CMD_REAL_ESTATE_ITEM_PLACEMENT_7                            459
#define EQ_EXECUTECMD_CMD_REAL_ESTATE_ITEM_PLACEMENT_8                            460
#define EQ_EXECUTECMD_CMD_REAL_ESTATE_ITEM_PLACEMENT_9                            461
#define EQ_EXECUTECMD_CMD_REAL_ESTATE_ITEM_PLACEMENT_10                           462
#define EQ_EXECUTECMD_CMD_REAL_ESTATE_ITEM_PLACEMENT_11                           463
#define EQ_EXECUTECMD_CMD_REAL_ESTATE_ITEM_PLACEMENT_12                           464
#define EQ_EXECUTECMD_CMD_REAL_ESTATE_LEAVE                                       465
#define EQ_EXECUTECMD_CMD_VOTE_RESULTS                                            466
#define EQ_EXECUTECMD_CMD_TOGGLE_TCG                                              467
#define EQ_EXECUTECMD_CMD_MOVE_DOWN                                               468
#define EQ_EXECUTECMD_CMD_STOP_ACTION                                             469
#define EQ_EXECUTECMD_CMD_TOGGLE_ALARM                                            470
#define EQ_EXECUTECMD_CMD_TOGGLE_BANK_BAGS                                        471
#define EQ_EXECUTECMD_TOGGLE_ZONE_GUIDE_WINDOW                                    472
#define EQ_EXECUTECMD_TOGGLE_ZONE_PATH_WINDOW                                     473
#define EQ_EXECUTECMD_CMD_MARKETPLACE_SILVER                                      474
#define EQ_EXECUTECMD_CMD_MARKETPLACE_GOLD                                        475
#define EQ_EXECUTECMD_CMD_HISTORIC_ALERTS                                         476
#define EQ_EXECUTECMD_CMD_SOCIAL_SHARE                                            477
#define EQ_EXECUTECMD_CMD_TOGGLE_AGGRO                                            478
#define EQ_EXECUTECMD_CMD_LOCK_AGGRO                                              479
#define EQ_EXECUTECMD_CMD_TOGGLE_BARTER_SEARCH                                    480
#define EQ_EXECUTECMD_CMD_OPEN_URL                                                481
#define EQ_EXECUTECMD_CMD_TOGGLE_TARGETOFTARGETWIN                                482
#define EQ_EXECUTECMD_CMD_RAID_DELEGATE_MAIN_ASSIST                               483
#define EQ_EXECUTECMD_CMD_INSPECT_BUFFS                                           484
#define EQ_EXECUTECMD_CMD_GROUP_DELEGATE_MARK_NPC                                 485
#define EQ_EXECUTECMD_CMD_RAID_DELEGATE_MARK_NPC                                  486
#define EQ_EXECUTECMD_CMD_GROUP_MARK_NPC_1                                        487
#define EQ_EXECUTECMD_CMD_GROUP_MARK_NPC_2                                        488
#define EQ_EXECUTECMD_CMD_GROUP_MARK_NPC_3                                        489
#define EQ_EXECUTECMD_CMD_RAID_MARK_NPC_1                                         490
#define EQ_EXECUTECMD_CMD_RAID_MARK_NPC_2                                         491
#define EQ_EXECUTECMD_CMD_RAID_MARK_NPC_3                                         492
#define EQ_EXECUTECMD_CMD_FIND_PC_GROUP_RAID                                      493
#define EQ_EXECUTECMD_CMD_TOGGLE_KEYRINGS                                         494
#define EQ_EXECUTECMD_CMD_GROUP_DELEGATE_MASTER_LOOTER                            495
#define EQ_EXECUTECMD_CMD_RAID_DELEGATE_MASTER_LOOTER                             496
#define EQ_EXECUTECMD_CMD_TOGGLE_ADVANCED_LOOT_WIN                                497
#define EQ_EXECUTECMD_CMD_TOGGLE_PICKZONE_WIN                                     498
#define EQ_EXECUTECMD_CMD_TOGGLE_TASK_OVERLAY_WIN                                 499
#define EQ_EXECUTECMD_CMD_TOGGLE_ITEM_OVERFLOW_WND                                500
#define EQ_EXECUTECMD_CMD_EVENT_CALENDAR                                          501
#define EQ_EXECUTECMD_CMD_TOGGLE_FINDITEM_WND                                     502
#define EQ_EXECUTECMD_CMD_HEROSJOURNEY_TEXT                                       503
#define EQ_EXECUTECMD_CMD_TOGGLE_FACTION_WND                                      504
#define EQ_EXECUTECMD_CMD_CHAT_TAB_NEXT                                           505
#define EQ_EXECUTECMD_CMD_CHAT_TAB_PREV                                           506
#define EQ_EXECUTECMD_TOGGLE_FPS                                                  507
#define EQ_EXECUTECMD_TOGGLE_AVATAR                                               508
#define EQ_EXECUTECMD_TOGGLE_PETITION                                             509
#define EQ_EXECUTECMD_TOGGLE_MEMINFO                                              510
#define EQ_EXECUTECMD_FLY_UP                                                      511
#define EQ_EXECUTECMD_FLY_DOWN                                                    512
#define EQ_EXECUTECMD_ADD_ROUTE                                                   513
#define EQ_EXECUTECMD_LAY_PPOINT                                                  514
#define EQ_EXECUTECMD_LAY_LINK                                                    515
#define EQ_EXECUTECMD_CONFIRM_YES                                                 516
#define EQ_EXECUTECMD_CONFIRM_NO                                                  517
#define EQ_EXECUTECMD_TARGET_PREV_NPC                                             518
#define EQ_EXECUTECMD_TARGET_NEXT_NPC                                             519
#define EQ_EXECUTECMD_ROTATE_STATS                                                520
#define EQ_EXECUTECMD_TOGGLE_NPC_TUNE                                             521
#define EQ_EXECUTECMD_TOGGLEQAMARKER                                              522
constexpr auto EQ_EXECUTECMD_ID_MAX = __LINE__ - EQ_EXECUTECMD_BEGIN_LINE - 2;

// unlisted commands
#define EQ_EXECUTECMD_CMD_EXITGAME                                                529    // "ExecuteCmd has received a CMD_EXITGAME.\n"
